# General Settings
title = "Ober - CV/Resume & Personal Portfolio Hugo Theme"
baseURL = "https://bslthemes.com/" #YOUR SITE URL
languageCode = "en-us"
theme = "ober"
resourceDir = "../resources"
paginate = 6
summaryLength = 20
DefaultContentLanguage = "en"

# Menu Settings
[menu]
[[menu.main]]
  identifier = "about"
  name = "About"
  url = "#about-section"
  weight = 1
[[menu.main]]
  identifier = "resume"
  name = "Resume"
  url = "#resume-section"
  weight = 2
[[menu.main]]
  identifier = "works"
  name = "Works"
  url = "#works-section"
  weight = 3
[[menu.main]]
  identifier = "pricing"
  name = "Pricing"
  url = "#pricing-section"
  weight = 4
[[menu.main]]
  identifier = "blog"
  name = "Blog"
  url = "#blog-section"
  weight = 5
[[menu.main]]
  identifier = "contact"
  name = "Contact"
  url = "#contact-section"
  weight = 6
[[menu.main]]
  identifier = "pages"
  name = "Pages"
  url = "#pages"
  weight = 7
[[menu.main]]
  identifier = "pages-blog"
  parent = "pages"
  name = "Blog List"
  url = "/blog/"
  weight = 1
[[menu.main]]
  identifier = "pages-works"
  parent = "pages"
  name = "Works List"
  url = "/portfolio/"
  weight = 2

# Main Settings
[params]
defaultSkin = "light"
dateFormat = "January 2, 2006"
authorName = "Federico Ober"
disqusComments = "test" #YOUR DISQUS COMMENTS SHORTNAME
formspreeURL = "" #YOUR FORMSPREE URL
googleAnalytics = "" #YOUR GOOGLE ANALYTICS CODE

# Preloader Settings
[params.preloader]
logo = "images/ober_logo.png"

# Header Settings
[params.header]
logo = "images/ober_logo.png"

# Footer Settings
[params.footer]
copyright = "Â© 2022 Ober. All Rights Reserved"
developer = "bslthemes"

# Social Settings
[[params.social]]
title = "Twitter"
icon = "fab fa-twitter"
url = "https://www.twitter.com/"
weight = 1
[[params.social]]
title = "Dribbble"
icon = "fab fa-dribbble"
url = "https://www.dribbble.com/"
weight = 2
[[params.social]]
title = "Behance"
icon = "fab fa-behance"
url = "https://www.behance.net/"
weight = 3

# Portfolio Settings
[params.portfolio]
homeNumOfItems = 12
[[params.portfolio.filters]]
name = "UI UX Design"
slug = "ui-ux-design"
[[params.portfolio.filters]]
name = "Photography"
slug = "photography"
[[params.portfolio.filters]]
name = "Development"
slug = "development"
[[params.portfolio.filters]]
name = "Branding"
slug = "branding"

# Sitemap Settings
[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"
